apiVersion: v1
kind: Service
metadata:
  name: cyberexpert-service
spec:
  selector:
    app: cyberexpert
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 8000
    nodePort: 31110
  type: NodePort
